// <auto-generated />
using System;
using Faculty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faculty.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Faculty.Models.Cathedra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Cathedras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кафедра Математического и Прикладного Анализа"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кафедра Вычислительной Математики и Прикладных Информационных Технологий"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Кафедра Математических Методов Исследования Операций"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Кафедра Математического Обеспечения ЭВМ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Кафедра ERP-систем и бизнес процессов"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Кафедра Системного анализа и управления"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Кафедра Программного Обеспечения и Администрирования Информационных Систем"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Лаборатория Вычислительной Техники"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Кафедра Механики и компьютерного моделирования"
                        });
                });

            modelBuilder.Entity("Faculty.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            Number = 5
                        });
                });

            modelBuilder.Entity("Faculty.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CathedraId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CathedraId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CathedraId = 6,
                            Name = "Абрамов Елисей Владленович"
                        },
                        new
                        {
                            Id = 2,
                            CathedraId = 8,
                            Name = "Аксёнов Казимир Ярославович"
                        },
                        new
                        {
                            Id = 3,
                            CathedraId = 4,
                            Name = "Родионов Гарри Львович"
                        },
                        new
                        {
                            Id = 4,
                            CathedraId = 3,
                            Name = "Фролов Рудольф Матвеевич"
                        },
                        new
                        {
                            Id = 5,
                            CathedraId = 2,
                            Name = "Ершов Константин Тимурович"
                        },
                        new
                        {
                            Id = 6,
                            CathedraId = 7,
                            Name = "Блинов Иосиф Адольфович"
                        },
                        new
                        {
                            Id = 7,
                            CathedraId = 1,
                            Name = "Комиссаров Августин Мэлсович"
                        },
                        new
                        {
                            Id = 8,
                            CathedraId = 8,
                            Name = "Исаков Юлий Павлович"
                        },
                        new
                        {
                            Id = 9,
                            CathedraId = 6,
                            Name = "Русаков Константин Денисович"
                        },
                        new
                        {
                            Id = 10,
                            CathedraId = 9,
                            Name = "Крылов Мстислав Владимирович"
                        },
                        new
                        {
                            Id = 11,
                            CathedraId = 7,
                            Name = "Гурьев Трофим Федорович"
                        },
                        new
                        {
                            Id = 12,
                            CathedraId = 5,
                            Name = "Селезнёв Кондратий Станиславович"
                        },
                        new
                        {
                            Id = 13,
                            CathedraId = 4,
                            Name = "Савин Панкрат Давидович"
                        },
                        new
                        {
                            Id = 14,
                            CathedraId = 5,
                            Name = "Ковалёв Юлий Мэлсович"
                        },
                        new
                        {
                            Id = 15,
                            CathedraId = 4,
                            Name = "Зыков Лев Вениаминович"
                        },
                        new
                        {
                            Id = 16,
                            CathedraId = 5,
                            Name = "Агафонов Виссарион Филатович"
                        },
                        new
                        {
                            Id = 17,
                            CathedraId = 6,
                            Name = "Соболев Федор Федотович"
                        },
                        new
                        {
                            Id = 18,
                            CathedraId = 9,
                            Name = "Блохин Константин Васильевич"
                        },
                        new
                        {
                            Id = 19,
                            CathedraId = 1,
                            Name = "Антонов Лев Тимофеевич"
                        },
                        new
                        {
                            Id = 20,
                            CathedraId = 5,
                            Name = "Русаков Вадим Робертович"
                        },
                        new
                        {
                            Id = 21,
                            CathedraId = 5,
                            Name = "Воробьёв Ибрагил Авдеевич"
                        },
                        new
                        {
                            Id = 22,
                            CathedraId = 3,
                            Name = "Баранов Антон Иосифович"
                        },
                        new
                        {
                            Id = 23,
                            CathedraId = 5,
                            Name = "Зимин Леонтий Дамирович"
                        },
                        new
                        {
                            Id = 24,
                            CathedraId = 7,
                            Name = "Панфилов Болеслав Протасьевич"
                        },
                        new
                        {
                            Id = 25,
                            CathedraId = 6,
                            Name = "Максимов Тарас Ростиславович"
                        },
                        new
                        {
                            Id = 26,
                            CathedraId = 4,
                            Name = "Брагин Арнольд Антонинович"
                        },
                        new
                        {
                            Id = 27,
                            CathedraId = 7,
                            Name = "Медведев Роберт Куприянович"
                        },
                        new
                        {
                            Id = 28,
                            CathedraId = 4,
                            Name = "Трофимов Эльдар Борисович"
                        },
                        new
                        {
                            Id = 29,
                            CathedraId = 4,
                            Name = "Панов Гурий Георгьевич"
                        },
                        new
                        {
                            Id = 30,
                            CathedraId = 9,
                            Name = "Смирнов Ефим Богданович"
                        },
                        new
                        {
                            Id = 31,
                            CathedraId = 3,
                            Name = "Власов Ибрагил Авксентьевич"
                        },
                        new
                        {
                            Id = 32,
                            CathedraId = 9,
                            Name = "Шубин Федор Геннадиевич"
                        },
                        new
                        {
                            Id = 33,
                            CathedraId = 1,
                            Name = "Белов Валерий Донатович"
                        },
                        new
                        {
                            Id = 34,
                            CathedraId = 6,
                            Name = "Панов Вилен Христофорович"
                        },
                        new
                        {
                            Id = 35,
                            CathedraId = 5,
                            Name = "Жуков Панкрат Евгеньевич"
                        },
                        new
                        {
                            Id = 36,
                            CathedraId = 3,
                            Name = "Кузьмин Аскольд Эльдарович"
                        },
                        new
                        {
                            Id = 37,
                            CathedraId = 2,
                            Name = "Пестов Сергей Протасьевич"
                        },
                        new
                        {
                            Id = 38,
                            CathedraId = 7,
                            Name = "Зуев Елисей Дмитриевич"
                        },
                        new
                        {
                            Id = 39,
                            CathedraId = 8,
                            Name = "Афанасьев Герасим Фролович"
                        },
                        new
                        {
                            Id = 40,
                            CathedraId = 1,
                            Name = "Костин Рудольф Алексеевич"
                        },
                        new
                        {
                            Id = 41,
                            CathedraId = 7,
                            Name = "Поляков Гордей Пантелеймонович"
                        },
                        new
                        {
                            Id = 42,
                            CathedraId = 2,
                            Name = "Буров Макар Феликсович"
                        },
                        new
                        {
                            Id = 43,
                            CathedraId = 1,
                            Name = "Ершов Петр Авдеевич"
                        },
                        new
                        {
                            Id = 44,
                            CathedraId = 4,
                            Name = "Максимов Игнат Оскарович"
                        },
                        new
                        {
                            Id = 45,
                            CathedraId = 7,
                            Name = "Некрасов Артур Мэлсович"
                        },
                        new
                        {
                            Id = 46,
                            CathedraId = 2,
                            Name = "Кудрявцев Вадим Владимирович"
                        },
                        new
                        {
                            Id = 47,
                            CathedraId = 3,
                            Name = "Мухин Власий Евсеевич"
                        },
                        new
                        {
                            Id = 48,
                            CathedraId = 6,
                            Name = "Горшков Тарас Петрович"
                        },
                        new
                        {
                            Id = 49,
                            CathedraId = 5,
                            Name = "Исаев Касьян Дмитриевич"
                        },
                        new
                        {
                            Id = 50,
                            CathedraId = 6,
                            Name = "Фролов Вениамин Всеволодович"
                        },
                        new
                        {
                            Id = 51,
                            CathedraId = 9,
                            Name = "Лазарев Ярослав Леонидович"
                        },
                        new
                        {
                            Id = 52,
                            CathedraId = 6,
                            Name = "Суворов Моисей Станиславович"
                        },
                        new
                        {
                            Id = 53,
                            CathedraId = 3,
                            Name = "Шубин Натан Александрович"
                        },
                        new
                        {
                            Id = 54,
                            CathedraId = 7,
                            Name = "Щукин Юстин Валентинович"
                        },
                        new
                        {
                            Id = 55,
                            CathedraId = 6,
                            Name = "Муравьёв Владислав Федорович"
                        },
                        new
                        {
                            Id = 56,
                            CathedraId = 3,
                            Name = "Лаврентьев Яков Всеволодович"
                        },
                        new
                        {
                            Id = 57,
                            CathedraId = 4,
                            Name = "Волков Клим Геласьевич"
                        },
                        new
                        {
                            Id = 58,
                            CathedraId = 7,
                            Name = "Цветков Семен Даниилович"
                        },
                        new
                        {
                            Id = 59,
                            CathedraId = 6,
                            Name = "Тимофеев Емельян Аркадьевич"
                        },
                        new
                        {
                            Id = 60,
                            CathedraId = 7,
                            Name = "Якушев Лев Никитевич"
                        },
                        new
                        {
                            Id = 61,
                            CathedraId = 9,
                            Name = "Денисов Кирилл Юрьевич"
                        },
                        new
                        {
                            Id = 62,
                            CathedraId = 6,
                            Name = "Филатов Аввакуум Пантелеймонович"
                        },
                        new
                        {
                            Id = 63,
                            CathedraId = 5,
                            Name = "Емельянов Рудольф Данилович"
                        },
                        new
                        {
                            Id = 64,
                            CathedraId = 6,
                            Name = "Архипов Аввакум Геннадьевич"
                        },
                        new
                        {
                            Id = 65,
                            CathedraId = 6,
                            Name = "Сергеев Овидий Христофорович"
                        },
                        new
                        {
                            Id = 66,
                            CathedraId = 7,
                            Name = "Рогов Виктор Эдуардович"
                        },
                        new
                        {
                            Id = 67,
                            CathedraId = 5,
                            Name = "Сергеев Велорий Созонович"
                        },
                        new
                        {
                            Id = 68,
                            CathedraId = 8,
                            Name = "Козлов Нинель Константинович"
                        },
                        new
                        {
                            Id = 69,
                            CathedraId = 9,
                            Name = "Шаров Владлен Романович"
                        },
                        new
                        {
                            Id = 70,
                            CathedraId = 1,
                            Name = "Пономарёв Леонард Андреевич"
                        },
                        new
                        {
                            Id = 71,
                            CathedraId = 3,
                            Name = "Коновалов Тарас Сергеевич"
                        },
                        new
                        {
                            Id = 72,
                            CathedraId = 9,
                            Name = "Лазарев Лев Леонидович"
                        },
                        new
                        {
                            Id = 73,
                            CathedraId = 1,
                            Name = "Никонов Оскар Артёмович"
                        },
                        new
                        {
                            Id = 74,
                            CathedraId = 1,
                            Name = "Галкин Митрофан Валерьянович"
                        },
                        new
                        {
                            Id = 75,
                            CathedraId = 7,
                            Name = "Харитонов Исак Михайлович"
                        },
                        new
                        {
                            Id = 76,
                            CathedraId = 3,
                            Name = "Васильев Мечеслав Улебович"
                        },
                        new
                        {
                            Id = 77,
                            CathedraId = 3,
                            Name = "Кононов Май Георгьевич"
                        },
                        new
                        {
                            Id = 78,
                            CathedraId = 1,
                            Name = "Кулагин Абрам Максович"
                        },
                        new
                        {
                            Id = 79,
                            CathedraId = 9,
                            Name = "Фомичёв Александр Филиппович"
                        },
                        new
                        {
                            Id = 80,
                            CathedraId = 4,
                            Name = "Буров Мартин Давидович"
                        },
                        new
                        {
                            Id = 81,
                            CathedraId = 1,
                            Name = "Кошелев Валентин Мартынович"
                        },
                        new
                        {
                            Id = 82,
                            CathedraId = 1,
                            Name = "Королёв Максимилиан Вадимович"
                        },
                        new
                        {
                            Id = 83,
                            CathedraId = 9,
                            Name = "Лыткин Роберт Донатович"
                        },
                        new
                        {
                            Id = 84,
                            CathedraId = 7,
                            Name = "Крюков Самуил Васильевич"
                        },
                        new
                        {
                            Id = 85,
                            CathedraId = 9,
                            Name = "Шарапов Харитон Федотович"
                        },
                        new
                        {
                            Id = 86,
                            CathedraId = 7,
                            Name = "Борисов Лука Андреевич"
                        },
                        new
                        {
                            Id = 87,
                            CathedraId = 7,
                            Name = "Ермаков Вадим Валентинович"
                        });
                });

            modelBuilder.Entity("Faculty.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CathedraId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CathedraId");

                    b.HasIndex("CourseId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CathedraId = 2,
                            CourseId = 4,
                            Name = "1 группа (Механика и мат. моделирование)"
                        },
                        new
                        {
                            Id = 2,
                            CathedraId = 4,
                            CourseId = 4,
                            Name = "21 группа (Фундаментальная математика и механика) УВЦ"
                        },
                        new
                        {
                            Id = 3,
                            CathedraId = 3,
                            CourseId = 5,
                            Name = "2 группа (ПМиИ)"
                        },
                        new
                        {
                            Id = 4,
                            CathedraId = 4,
                            CourseId = 2,
                            Name = "3 группа (ПМиИ)"
                        },
                        new
                        {
                            Id = 5,
                            CathedraId = 2,
                            CourseId = 4,
                            Name = "4 группа (ПМиИ)"
                        },
                        new
                        {
                            Id = 6,
                            CathedraId = 1,
                            CourseId = 1,
                            Name = "5 группа (ПМиИ)"
                        },
                        new
                        {
                            Id = 7,
                            CathedraId = 3,
                            CourseId = 1,
                            Name = "61 группа (ФИиИТ)"
                        },
                        new
                        {
                            Id = 8,
                            CathedraId = 6,
                            CourseId = 5,
                            Name = "71 группа (БИ)"
                        },
                        new
                        {
                            Id = 9,
                            CathedraId = 7,
                            CourseId = 5,
                            Name = "91 группа (МО и АИС)"
                        });
                });

            modelBuilder.Entity("Faculty.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MarkValueId")
                        .HasColumnType("int");

                    b.Property<int>("StatementId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarkValueId");

                    b.HasIndex("StatementId");

                    b.HasIndex("StudentId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("Faculty.Models.MarkValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("MarkValues");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Неудовлетворительно"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Удовлетворительно"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Хорошо"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Отлично"
                        });
                });

            modelBuilder.Entity("Faculty.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Очная"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Заочная"
                        });
                });

            modelBuilder.Entity("Faculty.Models.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Statements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            GroupId = 1,
                            PeriodBegin = new DateTime(2020, 6, 2, 0, 43, 11, 183, DateTimeKind.Local).AddTicks(4717),
                            PeriodEnd = new DateTime(2020, 6, 17, 0, 43, 11, 188, DateTimeKind.Local).AddTicks(363),
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("Faculty.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Ефремов Сергей Иосифович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 3,
                            IsActive = true,
                            Name = "Кабанов Кирилл Григорьевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Антонов Карл Филатович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            GroupId = 7,
                            IsActive = true,
                            Name = "Блинов Ян Пантелеймонович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Калашников Митрофан Глебович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            GroupId = 5,
                            IsActive = true,
                            Name = "Терентьев Юлиан Мэлорович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Журавлёв Панкратий Глебович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            GroupId = 3,
                            IsActive = true,
                            Name = "Власов Ермолай Данилович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Нестеров Мартин Тихонович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            GroupId = 7,
                            IsActive = true,
                            Name = "Рябов Августин Артёмович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Гордеев Арсен Ярославович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Суханов Матвей Кириллович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Фомичёв Леонид Вячеславович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Дроздов Константин Мэлсович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Марков Максимилиан Богданович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            GroupId = 3,
                            IsActive = true,
                            Name = "Абрамов Родион Константинович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Богданов Фрол Улебович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            GroupId = 3,
                            IsActive = true,
                            Name = "Силин Юлий Тарасович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Чернов Гордей Алексеевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Панов Дмитрий Артемович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Наумов Герасим Данилович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Панфилов Виссарион Валентинович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            GroupId = 5,
                            IsActive = true,
                            Name = "Вишняков Аркадий Проклович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 24,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Григорьев Лука Адольфович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 25,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Туров Герасим Миронович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            GroupId = 5,
                            IsActive = true,
                            Name = "Исаков Дональд Борисович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 27,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Фёдоров Алексей Степанович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Новиков Панкрат Митрофанович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 29,
                            GroupId = 5,
                            IsActive = true,
                            Name = "Селиверстов Артур Лукьевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 30,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Дмитриев Родион Рудольфович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Юдин Исак Онисимович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 32,
                            GroupId = 3,
                            IsActive = true,
                            Name = "Ситников Устин Витальевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 33,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Копылов Май Мэлсович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 34,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Дементьев Максимилиан Тарасович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 35,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Ефремов Демьян Лукьянович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 36,
                            GroupId = 5,
                            IsActive = true,
                            Name = "Кузнецов Архип Тимурович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 37,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Игнатов Аскольд Леонидович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 38,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Михеев Ермак Макарович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 39,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Щербаков Константин Анатольевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 40,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Кузнецов Овидий Ростиславович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 41,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Лаврентьев Касьян Пантелеймонович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 42,
                            GroupId = 7,
                            IsActive = true,
                            Name = "Гуляев Даниил Эльдарович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 43,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Доронин Вальтер Степанович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 44,
                            GroupId = 7,
                            IsActive = true,
                            Name = "Князев Давид Геласьевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 45,
                            GroupId = 5,
                            IsActive = true,
                            Name = "Крюков Авраам Алексеевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 46,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Мухин Исаак Геннадиевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 47,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Логинов Влас Данилович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 48,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Шарапов Агафон Христофорович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 49,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Киселёв Платон Григорьевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 50,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Нестеров Афанасий Феликсович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 51,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Соколов Ипполит Ярославович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 52,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Гусев Тимофей Константинович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 53,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Колобов Модест Яковович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 54,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Фёдоров Геннадий Федосеевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 55,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Андреев Богдан Егорович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 56,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Емельянов Ермак Артемович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 57,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Куликов Лука Мартынович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 58,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Александров Ростислав Созонович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 59,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Трофимов Руслан Проклович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 60,
                            GroupId = 7,
                            IsActive = true,
                            Name = "Уваров Максим Данилович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 61,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Беляев Арсений Аристархович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 62,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Коновалов Герасим Миронович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 63,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Белов Виталий Андреевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 64,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Фролов Варлаам Георгьевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 65,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Игнатов Ефим Геласьевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 66,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Зуев Кассиан Мэлсович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 67,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Горбунов Эдуард Тарасович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 68,
                            GroupId = 5,
                            IsActive = true,
                            Name = "Никитин Евгений Никитевич",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 69,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Максимов Кирилл Кириллович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 70,
                            GroupId = 5,
                            IsActive = true,
                            Name = "Кудрявцев Кассиан Егорович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 71,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Туров Нелли Еремеевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 72,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Лыткин Гордий Егорович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 73,
                            GroupId = 2,
                            IsActive = true,
                            Name = "Дорофеев Нелли Альбертович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 74,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Мышкин Нелли Егорович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 75,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Горшков Эрик Георгьевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 76,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Копылов Геннадий Феликсович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 77,
                            GroupId = 8,
                            IsActive = true,
                            Name = "Шаров Пантелей Созонович",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 78,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Голубев Клим Валерьевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 79,
                            GroupId = 4,
                            IsActive = true,
                            Name = "Журавлёв Севастьян Владленович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 80,
                            GroupId = 1,
                            IsActive = true,
                            Name = "Федотов Парамон Ярославович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 81,
                            GroupId = 3,
                            IsActive = true,
                            Name = "Кузнецов Донат Онисимович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 82,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Беляков Самуил Иринеевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 83,
                            GroupId = 9,
                            IsActive = true,
                            Name = "Меркушев Артем Валерьянович",
                            PaymentTypeId = 2
                        },
                        new
                        {
                            Id = 84,
                            GroupId = 7,
                            IsActive = true,
                            Name = "Соболев Корнелий Юрьевич",
                            PaymentTypeId = 1
                        },
                        new
                        {
                            Id = 85,
                            GroupId = 6,
                            IsActive = true,
                            Name = "Фролов Август Филиппович",
                            PaymentTypeId = 2
                        });
                });

            modelBuilder.Entity("Faculty.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Русский язык для устной и письменной коммуникации"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Физическая культура"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Иностранный язык "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Линейная алгебра"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Математический анализ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Информатика и программирование"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Дискретная математика"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Практикум на ЭВМ по программированию"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Аналитическая геометрия"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Пакеты прикладных программ"
                        },
                        new
                        {
                            Id = 11,
                            Name = "История"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Линейная алгебра"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Архитектура вычислительных систем"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Алгоритмы и анализ сложности"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Правоведение"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Теория вероятностей"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Языки и методы программирования"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Математическая логика и теория алгоритмов"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Базы данных"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Дифференциальные уравнения"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Физическая культура"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Неклассические логики"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Операционные системы"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Экономика"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Математическая статистика"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Вычислительные методы"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Архитектура современных микропроцессоров"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Проектирование информационных систем"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Физика"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Архитектура мобильных устройств"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Программирование на С#"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Математические основы компьютерной графики"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Компьютерные сети"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Компьютерная графика"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Основы облачных вычислений"
                        },
                        new
                        {
                            Id = 36,
                            Name = " Методы оптимизации"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Программируемые микроконтроллеры"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Java-программирование"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Введение в язык программирования Python"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Введение в Unix"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Информационная безопасность и защита информации"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Прикладная теория графов"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Философия"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Методы компиляции"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Реляционные СУБД"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Введение в UML-технологии"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Faculty.Models.Employee", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Faculty.Models.Cathedra", "Cathedra")
                        .WithMany()
                        .HasForeignKey("CathedraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Faculty.Models.Group", b =>
                {
                    b.HasOne("Faculty.Models.Cathedra", "Cathedra")
                        .WithMany()
                        .HasForeignKey("CathedraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Faculty.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Faculty.Models.Mark", b =>
                {
                    b.HasOne("Faculty.Models.MarkValue", "MarkValue")
                        .WithMany()
                        .HasForeignKey("MarkValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Faculty.Models.Statement", "Statement")
                        .WithMany("Marks")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Faculty.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Faculty.Models.Statement", b =>
                {
                    b.HasOne("Faculty.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Faculty.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Faculty.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Faculty.Models.Student", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Faculty.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Faculty.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
